### ISSUE TITLE
Shuffle Buffer or Mutable Array

### ISSUE THREAD

**Issue by tomijaga** [ZenVoich/fuzz#1]
Hey @ZenVoich,
I implemented thisshuffle function in one of my unit tests and thought it would be a good addition to this library.
It could potentially be included as a `.shuffle()` method in a new FuzzBuffer module, a FuzzArrayMut module, or perhaps even both.
If you're okay with it, I could submit a PR to add this feature.
 
 ```motoko 
    func shuffle_buffer<A>(fuzz : Fuzz.Fuzzer, buffer : Buffer.Buffer<A>) {
        for (i in Iter.range(0, buffer.size() - 3)) {
            let j = fuzz.nat.randomRange(i + 1, buffer.size() - 1);
            let tmp = buffer.get(i);
            buffer.put(i, buffer.get(j));
            buffer.put(j, tmp);
        };
    };
```

The `buffer-size() - 3` might be confusing but here's how the selection would look in the last iteration:
`buffer -> [..., i, i + 1, buffer.size() - 1]`

`j` could be `i + 1` or `buffer.size() - 1`

**Comment by ZenVoich** [comment]
Hi @tomijaga 

Useful feature!

> If you're okay with it, I could submit a PR to add this feature.

Yes, sure.

----

In base package it's starting to name mutable arrays as `var array` https://github.com/dfinity/motoko-base/issues/605, so I would suggest `FuzzArrayMut` -> `FuzzVarArray` 


`buffer.size() - 3` will trap on size < 3. It would be nice if it will work with any size(even 0).  You can take a look at this implementation https://github.com/flowerpowerdao/power-equalizer/blob/main/src/utils.mo#L200
