### ISSUE TITLE
randomAlphanumeric(30) returns a string of 31 chars

### ISSUE THREAD

**Issue by tiagoicp** [ZenVoich/fuzz#3]
Hi Zen,

Was using this package today and strangely the randomAlphanumeric(30) is returning 31 chars.
Eg: eYuerqcSz8WPWG3kUOP1kUyVPR9jnBJ

Can you double check what might be happening?

Thanks for this lib 👍

**Comment by ZenVoich** [comment]
Hi @tiagoicp, thanks for pointing this out.

There was a bug in text module, fixed in `0.2.1`
